nxhouse/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap as sitemap_view
from django.views.decorators.cache import cache_page, never_cache

from nxhouse import views, feeds, sitemap

urlpatterns = [
    url(r'^$', views.SectionListView.as_view(), name='index'),
    url(r'^new/$', never_cache(views.ItemCreateView.as_view()), name='item-new'),
    url(r'^edit/(?P<pk>\d+)/$', never_cache(views.ItemUpdateView.as_view()), name='item-edit'),
    url(r'^(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.ItemDetailView.as_view(), name='item'),
    url(r'^group/(?P<pk>\d+)-(?P<slug>[-\w]+)/$', views.GroupDetail.as_view(), name='group'),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^robots\.txt$', cache_page(60 * 60)(views.RobotsView.as_view()), name='robots'),
    url(r'^sitemap\.xml$', sitemap_view, {'sitemaps': sitemap.sitemaps_dict}, name='sitemap'),
    url(r'^rss\.xml$', cache_page(60 * 15)(feeds.LatestItemFeed()), name='rss'),
    url(r'^user/$', views.MyItemsView.as_view(), name='user-items'),
    url(r'^user/profile/$', views.ProfileView.as_view(), name='profile'),
    url(r'^user/my/delete/(?P<pk>\d+)/$', views.ItemDeleteView.as_view(), name='my-delete'),
    
    url(r'^auth/register/$', views.RegisterView.as_view(), name='auth-register'),
]

project/urls.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    # Authorization
    url(r'^user/', include('social_django.urls', namespace='social')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^', include('django.contrib.auth.urls')),
    url(r'^', include('nxhouse.urls', namespace='nxhouse')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nxhouse/models.py
# -*- coding:utf-8 -*-
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.functional import cached_property
from django.utils.six import python_2_unicode_compatible
from django.utils.translation import ugettext as _
from sorl.thumbnail import ImageField
from unidecode import unidecode

from nxhouse import settings as nxhouse_settings
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL)
    phone = models.CharField(_('phone'), max_length=30, null=True, blank=True)
    receive_news = models.BooleanField(_('receive news'), default=True, db_index=True)

    def allow_add_item(self):
        return self.user.item_set.count() < nxhouse_settings.NXHOUSE_ITEM_PER_USER_LIMIT

    @staticmethod
    def get_or_create_for_user(user):
        if hasattr(user, 'profile'):
            return user.profile
        else:
            return Profile.objects.create(user=user)


@python_2_unicode_compatible
class Section(models.Model):
    title = models.CharField(_('title'), max_length=100)

    def __str__(self):
        return self.title

    @cached_property
    def count(self):
        return Item.objects \
            .filter(is_active=True) \
            .filter(group__section=self) \
            .count()

    class Meta:
        verbose_name = _('section')
        verbose_name_plural = _('sections')


@python_2_unicode_compatible
class Group(models.Model):
    slug = models.SlugField(blank=True, null=True)
    title = models.CharField(_('title'), max_length=100)
    section = models.ForeignKey('Section', verbose_name=_('section'))

    def __str__(self):
        return '%s - %s' % (self.section.title, self.title)

    @cached_property
    def count(self):
        return self.item_set.filter(is_active=True).count()

    class Meta:
        verbose_name = _('group')
        verbose_name_plural = _('groups')
        ordering = ['section__title', 'title', ]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Group, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('nxhouse:group', kwargs={'pk': self.pk, 'slug': self.slug})


@python_2_unicode_compatible
class Item(models.Model):
    slug = models.SlugField(blank=True, null=True, max_length=100)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    group = models.ForeignKey(Group, verbose_name=_('group'))

    title = models.CharField(_('title'), max_length=100)
    description = models.TextField(_('description'))
    price = models.DecimalField(_('price'), max_digits=10, decimal_places=2)
    is_active = models.BooleanField(_('display'), default=True, db_index=True)
    updated = models.DateTimeField(_('updated'), auto_now=True, db_index=True)
    posted = models.DateTimeField(_('posted'), auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _('item')
        verbose_name_plural = _('items')
        ordering = ('-updated', )

    def get_absolute_url(self):
        return reverse('nxhouse:item', kwargs={
            'pk': self.pk,
            'slug': self.slug
        })

    def get_keywords(self):
        # TODO need more optimal keywords selection
        return ",".join(set(self.description.split()))

    @cached_property
    def image_count(self):
        return self.image_set.count()

    @cached_property
    def featured_image(self):
        return self.image_set.all().first()

    @cached_property
    def related_items(self):
        qs = Item.objects \
            .filter(is_active=True) \
            .filter(group=self.group) \
            .exclude(pk=self.pk)

        return qs[:nxhouse_settings.NXHOUSE_RELATED_LIMIT]

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(unidecode(self.title))
        super(Item, self).save(*args, **kwargs)


class Image(models.Model):
    item = models.ForeignKey(Item)
    file = ImageField(_('image'), upload_to='images')

nxhouse/forms.py
# -*- coding:utf-8 -*-
from django import forms
from django.utils.translation import ugettext as _
from django.contrib.auth.forms import UserRegistrationForm
from django.contrib.auth.models import User
from nxhouse.models import Item, Group, Profile
import logging
import re

class SearchForm(forms.Form):
    group = forms.ModelChoiceField(label=_('Group'), queryset=Group.objects.all(), required=False)
    q = forms.CharField(required=False, label=_('Query'),)
    price_from = forms.DecimalField(required=False, label=_('price_from'),)
    price_to = forms.DecimalField(required=False, label=_('price_to'),)

    def filter_by(self):
        # TODO search using more than one field
        # TODO split query string and make seaprate search by words
        logger = logging.getLogger(__name__)
        logger.error(self.cleaned_data)

        filters = {}
        filters['description__icontains'] = self.cleaned_data['q']

        if self.cleaned_data['group']:
            filters['group'] = self.cleaned_data['group']

        if self.cleaned_data['price_from'] is not None:
            filters['price__gte'] = self.cleaned_data['price_from']

        if self.cleaned_data['price_to'] is not None:
            filters['price__lte'] = self.cleaned_data['price_to']


        return filters


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('group', 'title', 'description', 'price', 'is_active')


class ProfileForm(forms.ModelForm):
    first_name = forms.CharField(required=False, label=_('First name'))
    last_name = forms.CharField(required=False, label=_('Last name'))
    
    def __init__(self, *args, **kw):
        super(ProfileForm, self).__init__(*args, **kw)
        self.fields['first_name'].initial = self.instance.user.first_name
        self.fields['last_name'].initial = self.instance.user.last_name

    def save(self, *args, **kw):
        initial = super(ProfileForm, self).save(*args, **kw)
        self.instance.user.first_name = self.cleaned_data.get('first_name')
        self.instance.user.last_name = self.cleaned_data.get('last_name')
        self.instance.user.save()
        return initial

    class Meta:
        model = Profile
        fields = ('phone', 'first_name', 'last_name')


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    #email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        if not re.match(r'[\w]{8,}', password1):
            raise forms.ValidationError("weak passwd")

        return password1

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'password1', 'password2', )

nxhouse/views.py
# -*- coding:utf-8 -*-
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse, reverse_lazy
from django.forms import inlineformset_factory
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.utils.translation import ugettext as _
from django.views.generic import DetailView, CreateView, UpdateView, ListView, DeleteView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import FormMixin

from nxhouse import settings as nxhouse_settings
from nxhouse.forms import ItemForm, ProfileForm, SearchForm, SignUpForm
from nxhouse.models import Item, Image, Group, Section, Profile

from django.contrib.auth.forms import UserCreationForm

class FilteredListView(FormMixin, ListView):
    def get_form_kwargs(self):
        return {
            'initial': self.get_initial(),
            'prefix': self.get_prefix(),
            'data': self.request.GET or None
        }

    def get(self, request, *args, **kwargs):
        self.object_list = self.get_queryset()

        form = self.get_form(self.get_form_class())

        if form.is_valid():
            self.object_list = self.object_list.filter(**form.filter_by())

        context = self.get_context_data(form=form)
        return self.render_to_response(context)


class SectionListView(ListView):
    model = Section


class SearchView(FilteredListView):
    form_class = SearchForm
    queryset = Item.objects.filter(is_active=True)
    paginate_by = 10
    template_name = 'nxhouse/search.html'


class FormsetMixin(object):
    object = None

    def get(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        return self.render_to_response(self.get_context_data(form=form, formset=formset))

    def post(self, request, *args, **kwargs):
        if getattr(self, 'is_update_view', False):
            self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_class = self.get_formset_class()
        formset = self.get_formset(formset_class)
        if form.is_valid() and formset.is_valid():
            return self.form_valid(form, formset)
        else:
            return self.form_invalid(form, formset)

    def get_formset_class(self):
        return self.formset_class

    def get_formset(self, formset_class):
        return formset_class(**self.get_formset_kwargs())

    def get_formset_kwargs(self):
        kwargs = {
            'instance': self.object
        }
        if self.request.method in ('POST', 'PUT'):
            kwargs.update({
                'data': self.request.POST,
                'files': self.request.FILES,
            })
        return kwargs

    def form_valid(self, form, formset):
        self.object = form.save()
        formset.instance = self.object
        formset.save()
        if hasattr(self, 'get_success_message'):
            self.get_success_message(form)
        return redirect(self.object.get_absolute_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(self.get_context_data(form=form, formset=formset))


class GroupDetail(SingleObjectMixin, ListView):
    paginate_by = nxhouse_settings.NXHOUSE_ITEM_PER_PAGE

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Group.objects.all())
        return super(GroupDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(GroupDetail, self).get_context_data(**kwargs)
        context['group'] = self.object
        return context

    def get_queryset(self):
        return self.object.item_set.all()


class ItemDetailView(DetailView):
    queryset = Item.objects.filter(is_active=True)


class ItemUpdateView(FormsetMixin, UpdateView):
    is_update_view = True
    model = Item
    form_class = ItemForm
    formset_class = inlineformset_factory(Item, Image, fields=('file',))

    def get_object(self, *args, **kwargs):
        obj = super(ItemUpdateView, self).get_object(*args, **kwargs)
        if not obj.user == self.request.user and not self.request.user.is_superuser:
            raise PermissionDenied
        return obj

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemUpdateView, self).dispatch(*args, **kwargs)


class ItemCreateView(FormsetMixin, CreateView):
    is_update_view = False
    model = Item
    form_class = ItemForm
    formset_class = inlineformset_factory(Item, Image, extra=3, fields=('file', ))

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        profile = Profile.get_or_create_for_user(self.request.user)
        if not profile.allow_add_item():
            messages.error(self.request, _('You have reached the limit!'))
            return redirect(reverse('nxhouse:user-items'))

        return super(ItemCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form, formset):
        form.instance.user = self.request.user
        form.save()

        return super(ItemCreateView, self).form_valid(form, formset)


class MyItemsView(ListView):
    template_name = 'nxhouse/user_item_list.html'

    def get_queryset(self):
        return Item.objects.filter(user=self.request.user)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(MyItemsView, self).dispatch(*args, **kwargs)


class ItemDeleteView(DeleteView):
    model = Item
    success_url = reverse_lazy('nxhouse:user-items')

    def get_queryset(self):
        qs = super(ItemDeleteView, self).get_queryset()

        if not self.request.user.is_superuser:
            qs = qs.filter(user=self.request.user)

        return qs

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ItemDeleteView, self).dispatch(*args, **kwargs)


class ProfileView(UpdateView):
    template_name = 'nxhouse/profile.html'
    form_class = ProfileForm
    success_url = reverse_lazy('nxhouse:profile')

    def get_object(self, queryset=None):
        return Profile.get_or_create_for_user(self.request.user)

    def form_valid(self, form):
        messages.success(self.request, _('Your profile settings was updated!'))
        return super(ProfileView, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ProfileView, self).dispatch(*args, **kwargs)


class RegisterView(CreateView):
    template_name = 'nxhouse/register.html'
    form_class = SignUpForm
    success_url = "/"
    
    def form_valid(self, form):
        messages.success(self.request, _('Your profile settings was updated!'))
        return super(RegisterView, self).form_valid(form)


class RobotsView(TemplateView):
    template_name = 'nxhouse/robots.txt'
    content_type = 'text/plain'

nxhouse/templates/nxhouse/_base.html
{% spaceless %}

  {% load staticfiles i18n %}

    <!DOCTYPE HTML>
    <html lang="en">

    <head>
        <title>{% block title %}{% endblock title %} | {{ NXHOUSE_SITE_NAME }}</title>

        <meta name="description" content="{% block meta_description %}{{ NXHOUSE_SITE_DESCRIPTION }}{% endblock meta_description %}" />
        <meta name="keywords" content="{% block meta_keywords %}{% endblock meta_keywords %}" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        {% if GOOGLE_SITE_VERIFICATION_ID %}
            <meta name="google-site-verification" content="{{ GOOGLE_SITE_VERIFICATION_ID }}" />
        {% endif %}
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

      {% if FACEBOOK_APP_ID %}
        <meta property="fb:app_id" content="{{ FACEBOOK_APP_ID }}"/>
      {% endif %}
      <meta property="og:type" content="website"/>
        {% block meta_og %}{% endblock %}

        <link rel="icon" type="image/x-icon" href="{% static 'nxhouse/img/favicon.ico' %}" />

      <link href="{% static 'nxhouse/css/bootstrap.min.css' %}" rel="stylesheet"/>
      <link href="{% static 'nxhouse/css/jumbotron-narrow.css' %}" rel="stylesheet"/>
        <link href="{% static 'nxhouse/css/lightbox.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'nxhouse/css/style.css' %}" rel="stylesheet" type="text/css"/>

      <link rel="alternate" type="application/rss+xml" href="{% url 'nxhouse:rss' %}">

    </head>

    <body>
    <div class="container" style="min-width:900px">

        <div class="header clearfix">
            <nav>
                <ul class="nav nav-pills pull-right">
                  <li role="presentation" class="active">
                    <a href="{% url 'nxhouse:item-new' %}">
                        +
                    </a>
                  </li>
                  <li role="presentation"><a href="{% url 'nxhouse:index' %}">{% trans "Home" %}</a></li>
                  <li role="presentation"><a href="{% url 'nxhouse:search' %}">{% trans "Search" %}</a></li>
                    {% if user.is_authenticated %}
                        <li role="presentation" class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <span class="glyphicon glyphicon-user"></span> {{ user.get_full_name }} <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu">
                              <li><a href="{% url 'nxhouse:user-items' %}">{% trans "My items" %} ({{ user.item_set.count }})</a>
                              </li>
                              <li>
                                <a href="{% url 'nxhouse:profile' %}">{% trans "Profile" %}</a>
                              </li>
                              <li class="divider"></li>
                              <li><a href="{% url 'logout' %}?next=/">{% trans "Logout" %}</a></li>
                            </ul>
                        </li>
                    {% else %}
                      <li role="presentation">
                        <a href="{% url 'nxhouse:profile' %}" title="{% trans "Login" %}">
                          <span class="glyphicon glyphicon-user"></span> {% trans "Login" %}
                        </a>
                      </li>
                      <li role="presentation">
                        <a href="{% url 'nxhouse:auth-register' %}" title="{% trans "Register" %}">
                          <span class="glyphicon glyphicon-user"></span> {% trans "Register" %}
                        </a>
                      </li>
                    {% endif %}
                </ul>
            </nav>
            <h3 class="text-muted">
                <a href="/">{{NXHOUSE_SITE_NAME}}</a>
            </h3>
        </div>

        {% if messages %}
            {% for message in messages %}
                <div class='row'>
                    <div class="col-md-12">
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            {{ message|safe }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        {% endif %}

        {% block body %}

        {% endblock %}

        <footer class="footer">
            <span class="pull-left">{{ NXHOUSE_SITE_NAME }}</span>
        </footer>

    </div>

    <script src="{% static 'nxhouse/js/jquery.min.js' %}"></script>
    <script src="{% static 'nxhouse/js/bootstrap.min.js' %}"></script>
    <script src="{%  static 'nxhouse/js/lightbox.min.js' %}"></script>

    {% block ext_scripts%}{% endblock %}

    {% if GOOGLE_ANALYTICS_PROPERTY_ID %}
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date();
                a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
                a.async = 1;
                a.src = g;
                m.parentNode.insertBefore(a, m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', '{{ GOOGLE_ANALYTICS_PROPERTY_ID }}', 'auto');
            ga('send', 'pageview');
        </script>
    {% endif %}

    <!-- generated {% now "jS F Y H:i:s" %} -->
    </body>
    </html>
{% endspaceless %}

nxhouse/templates/nxhouse/admin_toolbar.inc.html
{% load i18n %}

{% if user.is_superuser %}
    <div class="row">
        <div class="col-lg-12">
          [<a href='{% url 'nxhouse:my-delete' item.pk %}'>{% trans "Delete" %}</a>]
          [<a href='{% url 'nxhouse:item-edit' item.pk %}'>{% trans "Edit" %}</a>]
        </div>
    </div>
{% endif %}

nxhouse/templates/nxhouse/form_pagination.inc.html
{% load i18n %}

<nav>
    <ul class="pagination">
        <li>
            <button class="btn"
                name="page"
                value="{% if page_obj.has_previous %}{{ page_obj.previous_page_number }}{% endif %}"
                type="submit"
                {% if not page_obj.has_previous %}
                disabled="disabled"
                {% endif %}>
                {% trans "Prev" %}
            </button>
        </li>

        <li>
            <button class="btn"
                name="page"
                value="{% if page_obj.has_next %}{{ page_obj.next_page_number }}{% endif %}"
                type="submit"
                {% if not page_obj.has_next %}
                disabled="disabled"
                {% endif %}>
               {% trans "Next" %}
            </button>
        </li>
    </ul>
</nav>

nxhouse/templates/nxhouse/item_confirm_delete.html
{% extends "nxhouse/_base.html" %}

{% load humanize thumbnail i18n %}

{% block title %}{% trans "Delete" %} {{ object.title }}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
          <form method="post">
                {% csrf_token %}
                <p>
                    {% trans "Are you sure you want to delete" %}
                    <a href="{{ object.get_absolute_url }}">{{ object }}</a>?
                </p>
                <input type="submit" value="{% trans "Confirm" %}" class="btn btn-danger">
            </form>
        </div>
    </div>
{% endblock %}

nxhouse/templates/nxhouse/item_list.inc.html
{% load humanize thumbnail i18n%}

{% for object in object_list %}
    {% if forloop.first  %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <td></td>
                    <td>{% trans "Price" %}</td>
                </tr>
            </thead>
            <tbody>
    {%  endif %}
                <tr>
                    <td>
                      {% if object.featured_image %}
                        {% thumbnail object.featured_image.file "45x45" crop="center" as im %}
                          <a href='{{ object.get_absolute_url }}' title="{{ object.title }}">
                            <img
                                    src='{{ im.url }}'
                                    alt='{{ object.title }}'
                                    title='{{ object.title }}'
                                    width="{{ im.width }}"
                                    height="{{ im.height }}"
                                    class="img-rounded"
                            />
                            {% if object.image_count > 1 %}
                              <span class="badge badge-notify"
                                    title="{{ object.image_count|add:-1 }} {% trans 'more photos available' %}"> + {{ object.image_count|add:-1 }}</span>
                                    {% endif %}
                                </a>
                            {% endthumbnail %}
                        {% endif %}
                      <a href='{{ object.get_absolute_url }}' title='{{ object.title }}'>
                        {{ object.title }}
                        </a>
                    </td>
                    <td>
                        {{ object.price|default:"" }}
                    </td>
                </tr>
{% if forloop.last %}
        </tbody>
    </table>
{% endif %}

{% empty %}
    <p>
        {% trans "No item here yet." %}
      <a href="{% url 'nxhouse:item-new' %}">{% trans "Add one now!" %}</a>
    </p>
{% endfor %}

nxhouse/templates/nxhouse/search.html
{% extends "nxhouse/_base.html" %}

{% load i18n bootstrap %}

{% block title %}
    {% if form.q.value  %}{% trans "Search results for query" %} "{{ form.q.value }}" {% else %}{% trans "Search" %}{% endif %}
{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-6">
            <h3>{% trans "Search" %}</h3>
            <form method="get" role="form">
                {{ form|bootstrap }}
                <button type="submit" class="btn" name="page" value="1">{% trans "Search" %}</button>
                {% if object_list|length %}
                    {% include 'nxhouse/form_pagination.inc.html' %}
                {% endif %}
            </form>
        </div>
    </div>
    <div>
        <hr/>
        {% if object_list|length %}
            <h4>{% blocktrans %}Search results ({{ paginator.count }} items found):{% endblocktrans %}</h4>
            {% include "nxhouse/item_list.inc.html" with item=object %}
        {% else %}
            <h4>{% trans "Not found" %}</h4>
        {% endif %}
    </div>
{% endblock %}

nxhouse/templates/nxhouse/section_list.html
{% extends "nxhouse/_base.html" %}

{% block title %}{{ NXHOUSE_SITE_NAME }}{% endblock title %}

{% block body %}
    {% for object in object_list %}
        {% if forloop.first %}
            <div class="row marketing">
        {% endif %}

        <div class="col-lg-4">
          <h4>{{ object }} [{{ object.count }}]</h4>

            {% for group in object.group_set.all %}
                {% if group.count > 0 %}
                  <a href='{{ group.get_absolute_url }}' title="{{ group.title }}">
                    {{ group.title }} [{{ group.count }}]<br/>
                    </a>
                {% endif %}
            {% endfor %}
        </div>

        {% if forloop.counter|divisibleby:3 or forloop.last %}
            </div>
            {% if not forloop.last %}
                <div class="row marketing">
            {% endif %}
        {% endif %}
    {% endfor %}
{% endblock %}

nxhouse/templates/nxhouse/user_item_list.html
{% extends "nxhouse/_base.html" %}

{% load humanize i18n %}

{% block title %}{%  trans "My items" %}{% endblock title %}

{% block body %}
    <div class="row">
        <div class="col-lg-12">
            <h2>{%  trans "My items" %}</h2>
            {% for object in object_list %}
                {% if forloop.first  %}
                    <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <td>{%  trans "Group" %}</td>
                        <td>{%  trans "Update" %}</td>
                        <td>{%  trans "Link" %}</td>
                        <td>{%  trans "Price" %}</td>
                        <td>{%  trans "Posted" %}</td>
                        <td>{%  trans "Delete" %}</td>
                    </tr>
                    </thead>
                {%  endif %}
            <tr>
                <td><a href='{{ object.group.get_absolute_url }}'>{{object.group}}</a></td>
              <td><a href='{% url 'nxhouse:item-edit' object.pk %}' title='{% trans "Edit item" %}'>{{ object.title }}</a>
              </td>
              <td><a href='{{ object.get_absolute_url }}' title='{% trans "Open item" %}'>{% trans "Open" %}</a></td>
                <td>{{object.price|intcomma}}</td>
                <td>{{object.posted|date:"d.m.Y"}}</td>
              <td><a href='{% url 'nxhouse:my-delete' object.id %}'>{% trans "Delete" %}</a></td>
            </tr>

            {% if forloop.last  %}
                </table>
            {% endif %}

            {% empty %}
                <p>
                    {%  trans "You have no items to show." %}
                  <a href="{% url 'nxhouse:item-new' %}">{% trans "Add one now!" %}</a>
                </p>
            {% endfor %}
        </div>
    </div>
{% endblock %}